apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ako
  namespace: tanzu-continuousdelivery-resources
spec:
  type: "oci"
  interval: 5m0s
  url: oci://projects.registry.vmware.com/ako/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ako
  namespace: tanzu-continuousdelivery-resources
spec:
  releaseName: ako
  targetNamespace: avi-system
  interval: 10m
  chart:
    spec:
      chart: ako
      version: 1.11.3
      sourceRef:
        kind: HelmRepository
        name: ako
        namespace: tanzu-continuousdelivery-resources
  values:
    NetworkSettings:
      nsxtT1LR: "/infra/tier-1s/t1_aae18e07-6764-40cd-89ab-9d936c971f60_rtr" #supervisor namespace T1
      vipNetworkList:
      - networkName: vcf-ako-net-domain-c8:1ddcbef6-d1c1-4084-8bb3-8c1d3aebd931 # ingress network name
        cidr: 10.214.167.176/28 
    AKOSettings:
      clusterName: tap-run
      cniPlugin: antrea
    ControllerSettings:
      serviceEngineGroupName: domain-c8:1ddcbef6-d1c1-4084-8bb3-8c1d3aebd931   # Name of the ServiceEngine Group.
      controllerVersion: '22.1.5' # The controller API version
      cloudName: tanzu   # The configured cloud name on the Avi controller.
      controllerHost: '10.214.181.32' # IP address or Hostname of Avi Controller
      tenantName: admin   # Name of the tenant where all the AKO objects will be created in AVI.
    avicredentials:
      username: 'admin'
      password: 'VMware1!'
      # certificateAuthorityData:
    L7Settings:
      serviceType: NodePortLocal
    # Not available until 1.12
    # L4Settings:
    #   defaultLBController: "true"

  install:
    createNamespace: true