apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: disabled
    pod-security.kubernetes.io/enforce: privileged
  name: istio-system
---
apiVersion: ako.vmware.com/v1alpha2
kind: L4Rule
metadata:
  name: proxy-protocol
  namespace: istio-system
spec:
  applicationProfileRef: L4-app-proxy-protocol